"""Shared enums for the application."""
from enum import Enum


class UserRole(str, Enum):
    SUPER_ADMIN = "SUPER_ADMIN"
    ADMIN = "ADMIN"
    DEALER = "DEALER"
    USER = "USER"
    GUEST = "GUEST"


class UserStatus(str, Enum):
    ACTIVE = "ACTIVE"
    PENDING = "PENDING"
    SUSPENDED = "SUSPENDED"
    BANNED = "BANNED"


class CarStatus(str, Enum):
    DRAFT = "DRAFT"
    PENDING = "PENDING"
    ACTIVE = "ACTIVE"
    REJECTED = "REJECTED"
    PAUSED = "PAUSED"
    SOLD = "SOLD"
    EXPIRED = "EXPIRED"
    DELETED = "DELETED"


class CarCondition(str, Enum):
    NEW = "NEW"
    USED = "USED"
    CERTIFIED = "CERTIFIED"


class FuelType(str, Enum):
    PETROL = "PETROL"
    DIESEL = "DIESEL"
    HYBRID = "HYBRID"
    ELECTRIC = "ELECTRIC"
    PLUGIN_HYBRID = "PLUGIN_HYBRID"
    LPG = "LPG"
    CNG = "CNG"


class Transmission(str, Enum):
    AUTOMATIC = "AUTOMATIC"
    MANUAL = "MANUAL"
    SEMI_AUTOMATIC = "SEMI_AUTOMATIC"
    CVT = "CVT"


class DriveType(str, Enum):
    FWD = "FWD"
    RWD = "RWD"
    AWD = "AWD"
    FOUR_WD = "FOUR_WD"


class BodyType(str, Enum):
    SEDAN = "SEDAN"
    SUV = "SUV"
    COUPE = "COUPE"
    HATCHBACK = "HATCHBACK"
    WAGON = "WAGON"
    PICKUP = "PICKUP"
    VAN = "VAN"
    MOTORCYCLE = "MOTORCYCLE"
    TRUCK = "TRUCK"
    ELECTRIC = "ELECTRIC"
    CONVERTIBLE = "CONVERTIBLE"
    MINIVAN = "MINIVAN"
    CROSSOVER = "CROSSOVER"


class ReportReason(str, Enum):
    SCAM = "SCAM"
    FAKE_LISTING = "FAKE_LISTING"
    INCORRECT_INFO = "INCORRECT_INFO"
    DUPLICATE = "DUPLICATE"
    OFFENSIVE = "OFFENSIVE"
    SOLD_VEHICLE = "SOLD_VEHICLE"
    OTHER = "OTHER"


class ReportStatus(str, Enum):
    PENDING = "PENDING"
    REVIEWING = "REVIEWING"
    RESOLVED = "RESOLVED"
    REJECTED = "REJECTED"


class NotificationType(str, Enum):
    NEW_MESSAGE = "NEW_MESSAGE"
    LISTING_APPROVED = "LISTING_APPROVED"
    LISTING_REJECTED = "LISTING_REJECTED"
    LISTING_EXPIRED = "LISTING_EXPIRED"
    LISTING_SOLD = "LISTING_SOLD"
    PRICE_CHANGED = "PRICE_CHANGED"
    NEW_LOGIN = "NEW_LOGIN"
    SYSTEM = "SYSTEM"


class PaymentStatus(str, Enum):
    PENDING = "PENDING"
    PAID = "PAID"
    FAILED = "FAILED"
    REFUNDED = "REFUNDED"
    CANCELLED = "CANCELLED"


class PromotionType(str, Enum):
    FEATURED = "FEATURED"
    TOP_LISTING = "TOP_LISTING"
    HOMEPAGE = "HOMEPAGE"
    HIGHLIGHTED = "HIGHLIGHTED"
    DEALER_PROMOTION = "DEALER_PROMOTION"


class AuditAction(str, Enum):
    ADMIN_APPROVED_LISTING = "ADMIN_APPROVED_LISTING"
    ADMIN_REJECTED_LISTING = "ADMIN_REJECTED_LISTING"
    ADMIN_HID_LISTING = "ADMIN_HID_LISTING"
    ADMIN_DELETED_LISTING = "ADMIN_DELETED_LISTING"
    ADMIN_SUSPENDED_USER = "ADMIN_SUSPENDED_USER"
    ADMIN_BANNED_USER = "ADMIN_BANNED_USER"
    ADMIN_RESTORED_USER = "ADMIN_RESTORED_USER"
    ADMIN_VERIFIED_USER = "ADMIN_VERIFIED_USER"
    ADMIN_RESOLVED_REPORT = "ADMIN_RESOLVED_REPORT"
    SUPER_ADMIN_CREATED_ADMIN = "SUPER_ADMIN_CREATED_ADMIN"
    SUPER_ADMIN_DELETED_ADMIN = "SUPER_ADMIN_DELETED_ADMIN"
    SUPER_ADMIN_SUSPENDED_ADMIN = "SUPER_ADMIN_SUSPENDED_ADMIN"
    SUPER_ADMIN_CREATED_ROLE = "SUPER_ADMIN_CREATED_ROLE"
    SUPER_ADMIN_UPDATED_ROLE = "SUPER_ADMIN_UPDATED_ROLE"
    SUPER_ADMIN_DELETED_ROLE = "SUPER_ADMIN_DELETED_ROLE"
    SUPER_ADMIN_CHANGED_PERMISSION = "SUPER_ADMIN_CHANGED_PERMISSION"
    SUPER_ADMIN_UPDATED_SETTINGS = "SUPER_ADMIN_UPDATED_SETTINGS"
    USER_CREATED_LISTING = "USER_CREATED_LISTING"
    USER_DELETED_LISTING = "USER_DELETED_LISTING"
    USER_LOGIN = "USER_LOGIN"
    USER_REGISTERED = "USER_REGISTERED"


class Currency(str, Enum):
    USD = "USD"
    EUR = "EUR"
    AMD = "AMD"
    RUB = "RUB"
    GBP = "GBP"